services:
  frontend:
    build:
      context: ./deal-management-frontend
    ports:
      - "3000:80"
    networks:
      - app-network

  backend:
    build:
      context: ./DealManagementSystem
    ports:
      - "7216:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
